### ISSUE TITLE
Add support for custom 404 page

### ISSUE THREAD

**Issue by patrickdappollonio** [patrickdappollonio/http-server#120]
We should allow people to specify a custom 404 page.

**Comment by n00nchi** [comment]
Can I pick this up?

**Comment by patrickdappollonio** [comment]
You absolutely can! I might be a bit opinionated as to how this should play (as in, the router should configure a not found instead of a middleware).

The two requirements are:

* Being able to specify a 404 file to display.
* Being able to change the header to a status code, say, `200` if the user wishes to do so

Other than that, feel free to give it a shot!
