### ISSUE TITLE
Large files cause server to crash

### ISSUE THREAD

**Issue by gehoernchen** [patrickdappollonio/http-server#134]
Hi, I wanted to use this to provide a very large file, 9 GB in size, via this server.

I am running it behind a Traefik reverse proxy in Docker Compose. When trying to download the file, the RAM fills up with something (supposedly the file?) and the CPU is increasing heavily in utilization. Since the server only has 8 GB of RAM, at around 7.75 GB, the process is getting killed at that point. Thus, the file cannot be downloaded.

Docker is logging this to journalctl:
```
Oct 23 16:17:06 gehoernchen dockerd[565]: time="2024-10-23T16:17:06.486953368Z" level=info msg="ignoring event" container=d65de97d2fc711fdc2c89a7d981d03e41df55487007fa9d45f09f45f75931d43 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
```

**Comment by patrickdappollonio** [comment]
Hey!

Thanks for the report, can you try with `--disable-etag`?

**Comment by gehoernchen** [comment]
Yeah, that worked. Thank you!

**Comment by patrickdappollonio** [comment]
No worries! We've going around the block around etag handling and I think the most sensible thing to do is to disable etag generation for large files. I had some ideas put together that I'll push pretty soon, but this would give you the best of both worlds: smaller files get etagged which improves speed, and large files get ignored by etags.

Expect an update soon!

**Comment by patrickdappollonio** [comment]
Duplicate of https://github.com/patrickdappollonio/http-server/issues/63
