### ISSUE TITLE
Time attributes for the file and directory

### ISSUE THREAD

**Issue by hynoor** [patrickdappollonio/http-server#20]
Can we add more attributes such as 'created time', 'modify time' and 'access time' for the listing files and directories? now it only shows file type and size info.
![image](https://user-images.githubusercontent.com/12496127/195501455-d421dad1-bb3f-4962-89ca-9943a73c85ab.png)

**Comment by patrickdappollonio** [comment]
Hey @hynoor! I think this is a great idea and definitely am adding it to the next batch of updates.

In a somewhat side note, I think this will come right after https://github.com/patrickdappollonio/http-server/issues/13 is completed. May I ask you if you have any feedback you think might affect your usage of `http-server` if we move such change forward? Let me know!

**Comment by patrickdappollonio** [comment]
Hey @hynoor!

Not sure if you've been able to see the latest update, where the output looks like this:

![image](https://user-images.githubusercontent.com/930925/209422854-6fc074c8-4706-4915-88af-aee0bd837cb6.png)

Adding all the times (`atime`, `ctime`, `mtime`) in this table fashion might not be what we want. In fact, on small screens, the "modified time" is hidden from the view. I'm thinking about adding a popup div on top of everything that would print these values.

Do you have any feedback?
